### ISSUE TITLE
[CN][todo] 待完成统计

### ISSUE THREAD

**Issue by Teages** [CytoidCommunity/Cytoid-wiki#20]
A to-do list for 

## 游玩
- [ ] 游玩
- [ ] 开始游戏
- [ ] 游戏机制

## 制谱
- [ ] 谱面制作
- [ ] cyl教程
- [ ] PCtyx教程
- [ ] 注意事项
- [ ] 资源整合

##活动
- [ ] 实时更新游戏活动 (预告发布1天内)
- [ ] 实时更新周边活动 (结束后1周内)
- [ ] 实时更新相关比赛 (结束后3周内)

## 更新
- [ ] 删掉 Wiki 更新记录
- [ ] 及时更新Cytoid新版本 (发布后一周内)
